title: "Vivian Reutens"
author: "Vivian Reutens"
description: "New York University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: false                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_siblings: false            # show prev/next links

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "Writing", file: "writing.md", sidebaricon: pencil}
  - {title: "Experience", file: "experience.md", sidebaricon: briefcase}
  - {title: "Recs", file: "bookrecs.md", sidebaricon: books}
  - {title: "Contact", file: "contact.md", sidebaricon: envelope}

footer: ""

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
